#!/usr/bin/env node
// Generate src/tokens.css (CSS custom properties) and src/tokens.ts (typed object) from the token files.
// Run: pnpm --filter @strata/design-system tokens:build
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { cssVarName, flatten, validate, valueToCss } from "./dtcg.mjs";

const pkg = join(dirname(fileURLToPath(import.meta.url)), "..");
export const BASE_FILE = join(pkg, "tokens", "infora.tokens.json");
export const COMPONENT_FILE = join(pkg, "tokens", "strata.component.tokens.json");

export function loadTokens(baseFile = BASE_FILE, componentFile = COMPONENT_FILE) {
  const base = JSON.parse(readFileSync(baseFile, "utf8"));
  const component = JSON.parse(readFileSync(componentFile, "utf8"));
  const baseFlat = flatten(base);
  const baseCheck = validate(base);
  const componentCheck = validate(component, { external: new Map(baseFlat.map((t) => [t.path, t])) });
  const errors = [
    ...baseCheck.errors.map((e) => `infora.tokens.json ${e}`),
    ...componentCheck.errors.map((e) => `strata.component.tokens.json ${e}`),
  ];
  if (errors.length) {
    throw new Error(`Token validation failed:\n  ${errors.join("\n  ")}`);
  }
  const flat = [...baseFlat, ...flatten(component)];
  const byPath = new Map(flat.map((t) => [t.path, t]));
  const resolved = new Map();
  const resolve = (path, seen = new Set()) => {
    if (resolved.has(path)) return resolved.get(path);
    if (seen.has(path)) throw new Error(`Alias cycle at ${path}`);
    seen.add(path);
    const t = byPath.get(path);
    const css = valueToCss(t.type, t.value, (target) => resolve(target, seen));
    resolved.set(path, css);
    return css;
  };
  const list = flat.map((t) => ({
    path: t.path,
    cssVar: cssVarName(t.path),
    type: t.type ?? "string",
    css: valueToCss(t.type, t.value, (target) => `var(${cssVarName(target)})`),
    value: resolve(t.path),
    group: baseFlat.some((b) => b.path === t.path) ? "base" : "component",
  }));
  const provisional = Boolean(base.$extensions?.strata?.provisional);
  return { list, provisional, reason: base.$extensions?.strata?.reason ?? null };
}

function nest(list, pick) {
  const root = {};
  for (const t of list) {
    const parts = t.path.split(".");
    let node = root;
    for (const p of parts.slice(0, -1)) node = node[p] ??= {};
    node[parts.at(-1)] = pick(t);
  }
  return root;
}

export function renderCss({ list }) {
  const lines = list.map((t) => `  ${t.cssVar}: ${t.css};`);
  const durations = list.filter((t) => t.type === "duration").map((t) => `    ${t.cssVar}: 0ms;`);
  return [
    "/* Generated by scripts/build-tokens.mjs from tokens/*.tokens.json. Do not edit. */",
    ":root {",
    ...lines,
    "}",
    "",
    "/* Reduced motion: every duration becomes zero. */",
    "@media (prefers-reduced-motion: reduce) {",
    "  :root {",
    ...durations,
    "  }",
    "}",
    "",
  ].join("\n");
}

export function renderTs({ list, provisional, reason }) {
  const vars = nest(list, (t) => `var(${t.cssVar})`);
  const values = nest(list, (t) => t.value);
  const meta = list.map((t) => ({ path: t.path, cssVar: t.cssVar, type: t.type, value: t.value, group: t.group }));
  return [
    "// Generated by scripts/build-tokens.mjs from tokens/*.tokens.json. Do not edit.",
    "",
    "/** CSS variable references, for example tokens.color.bg.base is \"var(--color-bg-base)\". */",
    `export const tokens = ${JSON.stringify(vars, null, 2)} as const;`,
    "",
    "/** Resolved CSS values. Use these only where CSS variables cannot work, for example in a canvas. */",
    `export const tokenValues = ${JSON.stringify(values, null, 2)} as const;`,
    "",
    "/** Every token with its path, CSS variable and resolved value. */",
    `export const tokenList = ${JSON.stringify(meta, null, 2)} as const;`,
    "",
    "export type TokenPath = (typeof tokenList)[number][\"path\"];",
    "",
    `export const tokenMeta = ${JSON.stringify({ provisional, reason })} as const;`,
    "",
  ].join("\n");
}

export function build(outDir = join(pkg, "src")) {
  const data = loadTokens();
  mkdirSync(outDir, { recursive: true });
  writeFileSync(join(outDir, "tokens.css"), renderCss(data));
  writeFileSync(join(outDir, "tokens.ts"), renderTs(data));
  return data;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  try {
    const data = build();
    const note = data.provisional ? " (provisional tokens)" : "";
    console.log(`tokens: wrote ${data.list.length} tokens to src/tokens.css and src/tokens.ts${note}`);
  } catch (err) {
    console.error(String(err instanceof Error ? err.message : err));
    process.exit(1);
  }
}
