/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alerts
         * @description Alerts with their status. Tier 0 alerts appear as unconfirmed before any approval.
         */
        get: operations["alerts_api_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge Alert
         * @description AlertAcknowledged with the user as the actor. A second acknowledgement writes nothing.
         */
        post: operations["acknowledge_alert_api_alerts__alert_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm Alert
         * @description AlertConfirmed. 409 when the alert is already decided.
         */
        post: operations["confirm_alert_api_alerts__alert_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/alerts/{alert_id}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dismiss Alert
         * @description AlertDismissed with a reason. false_positive marks a wrong alert (telemetry: rate for each tier rule).
         */
        post: operations["dismiss_alert_api_alerts__alert_id__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Briefs */
        get: operations["list_briefs_api_briefs_get"];
        put?: never;
        /** Create Brief */
        post: operations["create_brief_api_briefs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefs/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Brief Diff */
        get: operations["brief_diff_api_briefs_diff_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefs/{version}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Brief */
        get: operations["get_brief_api_briefs__version__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/briefs/{version}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Brief */
        post: operations["activate_brief_api_briefs__version__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Calendar
         * @description Forecast procurement windows on a time axis. Projects without a date show their stage only.
         *
         *     Each item has the forecast detail (the intervals, the supporting projects and the evidence ids) and the stage
         *     evidence (stage_event_id, stage_evidence_ids).
         */
        get: operations["calendar_api_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stages
         * @description Deal stages (Kanban columns), lifecycle stages and the engagement window.
         */
        get: operations["stages_api_config_stages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/taxonomy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Taxonomy
         * @description Codes and names for the filters of the signal feed and the map.
         */
        get: operations["taxonomy_api_config_taxonomy_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deals
         * @description Opportunities with their stage and pending stage (Kanban board).
         */
        get: operations["deals_api_deals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{deal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deal Detail */
        get: operations["deal_detail_api_deals__deal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{deal_id}/contacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Contact
         * @description ContactAdded. The name, business email and business phone are encrypted with the key of the person.
         */
        post: operations["add_contact_api_deals__deal_id__contacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{deal_id}/next-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Next Action */
        post: operations["set_next_action_api_deals__deal_id__next_action_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{deal_id}/prequalification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Prequalification */
        post: operations["set_prequalification_api_deals__deal_id__prequalification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{deal_id}/relationship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deal Relationship
         * @description Buyer roles, contacts, touchpoints, next action and prequalification status for one opportunity.
         */
        get: operations["deal_relationship_api_deals__deal_id__relationship_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{deal_id}/stage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Move Stage
         * @description A DealStageChanged proposal (policy review). The card shows the pending stage until an approver decides.
         */
        post: operations["move_stage_api_deals__deal_id__stage_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/deals/{deal_id}/touchpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log Touchpoint */
        post: operations["log_touchpoint_api_deals__deal_id__touchpoints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/demand-drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Demand Drivers
         * @description Market events that change diesel demand for all customers (stream 'market').
         */
        get: operations["demand_drivers_api_demand_drivers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entities
         * @description Search entities by name (trigram similarity).
         */
        get: operations["entities_api_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/entities/{entity_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entity Detail
         * @description An entity with its facts, relationships and recent signals. `as_of` gives the state at a past time.
         */
        get: operations["entity_detail_api_entities__entity_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Evidence
         * @description Evidence items: the quote with its span offsets and a link to the source.
         *
         *     For a source with licence full, the response also gives a short text window around the span,
         *     so the frontend can highlight the span in context. For other licences it gives the quote only.
         */
        get: operations["evidence_api_evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Map Layers
         * @description Sites with coordinates, opportunities at those sites, and counts of recent signals by site.
         *
         *     Provenance (docs/07 rule 1): each site has identity_evidence_ids, status_event_id, status_evidence_ids and the
         *     geometry_source (the dataset of the coordinates). Each deal has evidence_ids, stage_event_id and
         *     stage_evidence_ids. Each project has stage_evidence_ids and the forecast evidence.
         */
        get: operations["map_layers_api_map_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Person
         * @description A person entity with its business contact data. After erasure the personal fields are empty.
         */
        get: operations["get_person_api_persons__person_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/persons/{person_id}/erase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Erase Person
         * @description Delete the key of the person. The history stays intact. The personal fields become unreadable.
         */
        post: operations["erase_person_api_persons__person_id__erase_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Priority
         * @description Opportunities ranked by lead time, demand estimate, confidence and buyer fit, with the breakdown.
         *
         *     The list shows the groups of config/priority.yaml in order. In each group, a deal whose project is in the
         *     engagement window and has no contact found comes first (docs/05 scorer rule 6), then the other deals by score.
         *     Each part of priority_breakdown has its value, score, weight, contribution, event_ids and evidence_ids.
         */
        get: operations["priority_api_priority_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Projects
         * @description Projects by lifecycle stage, with the engagement window flag and the forecast.
         */
        get: operations["projects_api_projects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Detail */
        get: operations["project_detail_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Proposals
         * @description The approval queue: each proposal with its proposed events and its evidence items (quote, span offsets,
         *     source url, title and publisher). status=pending gives the open queue.
         */
        get: operations["list_proposals_api_proposals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Proposal */
        get: operations["get_proposal_api_proposals__proposal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Proposal
         * @description Approve: the governance service writes the proposed events. 403 for the creator of the proposal.
         */
        post: operations["approve_proposal_api_proposals__proposal_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/approve-source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Approve Source
         * @description Approve a SourceProposed proposal: a new brief version with the source, active at once.
         */
        post: operations["approve_source_api_proposals__proposal_id__approve_source_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/edit-approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Edit Approve Proposal
         * @description Edit and approve: human events that keep the original evidence. 403 for the creator of the proposal.
         */
        post: operations["edit_approve_proposal_api_proposals__proposal_id__edit_approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/proposals/{proposal_id}/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reject Proposal
         * @description Reject with a reason (422 without). No event goes to the record.
         */
        post: operations["reject_proposal_api_proposals__proposal_id__reject_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quarantine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Quarantine */
        get: operations["list_quarantine_api_quarantine_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/quarantine/{quarantine_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Quarantine */
        get: operations["get_quarantine_api_quarantine__quarantine_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Login */
        post: operations["session_login_api_session_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Session Logout */
        post: operations["session_logout_api_session_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Signals
         * @description All in-scope items with filters by tier, sector, geography, theme, entity and text.
         */
        get: operations["signals_api_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sites
         * @description Sites with status, pending status, operator and last signal. watch=all gives the daily and weekly lists.
         *
         *     Each fact has its provenance (docs/07 rule 1): identity_evidence_ids (the first EntityIdentified), status_event_id
         *     and status_evidence_ids (the last SiteStatusChanged), operator_event_id and operator_evidence_ids, and
         *     last_signal_id and last_signal_evidence_ids.
         */
        get: operations["sites_api_sites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Health
         * @description For each source of the active brief: last success, error rate, documents per run, last error, next run.
         */
        get: operations["source_health_api_sources_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/known-gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Known Gaps */
        get: operations["known_gaps_api_sources_known_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Manual Upload
         * @description An analyst uploads a file (multipart: file, title, publisher, licence_code, url) or a URL (JSON).
         */
        post: operations["manual_upload_api_sources_manual_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources/{source_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_api_sources__source_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/telemetry/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alert Telemetry
         * @description For each alert: the published, fetched and raised timestamps, the delivery time for each channel, the
         *     acknowledgement time and user, and the outcome with the tier rule. Metrics: latency from fetch to alert
         *     (median, p90), time to acknowledgement (median, p90) and the false positive rate for each tier rule.
         */
        get: operations["alert_telemetry_api_telemetry_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ticker": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ticker
         * @description The latest Tier 0 and Tier 1 signals, and counts by tier for the last 24 hours and 7 days.
         */
        get: operations["ticker_api_ticker_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Timeline
         * @description The events of one entity, project or deal, with evidence links, up to `as_of`.
         */
        get: operations["timeline_api_timeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertConfirm */
        AlertConfirm: {
            /** Reason */
            reason?: string | null;
        };
        /** AlertDismiss */
        AlertDismiss: {
            /**
             * False Positive
             * @default false
             */
            false_positive: boolean;
            /** Reason */
            reason: string;
        };
        /**
         * AlertState
         * @description The alert after an acknowledgement or a decision.
         */
        AlertState: {
            /** Acknowledged At */
            acknowledged_at: string | null;
            /** Acknowledged By */
            acknowledged_by: string | null;
            /** Decided At */
            decided_at: string | null;
            /** Decided By */
            decided_by: string | null;
            /** Decision Reason */
            decision_reason: string | null;
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "unconfirmed" | "confirmed" | "dismissed" | "false_positive";
            /** Tier */
            tier: number;
            /** Tier Rule */
            tier_rule: string;
            /** Title */
            title: string;
        };
        /** ApproveResult */
        ApproveResult: {
            /** Event Ids */
            event_ids: string[];
            /** Proposal Id */
            proposal_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "approved" | "edited_approved";
        };
        /** Contact */
        Contact: {
            /** Email */
            email?: string | null;
            /** Found Via */
            found_via: string;
            /** Name */
            name?: string | null;
            /** Organisation Id */
            organisation_id?: string | null;
            /**
             * Person Id
             * @description An existing person entity. Without it, the business email (or the name and the organisation) finds or creates the person.
             */
            person_id?: string | null;
            /** Phone */
            phone?: string | null;
            /** Role */
            role: string;
        };
        /** DeliveryStatus */
        DeliveryStatus: {
            /** Email */
            email: string | null;
            /** Frontend */
            frontend: string | null;
        };
        /** DeliveryTimes */
        DeliveryTimes: {
            /** Email */
            email: string | null;
            /** Frontend */
            frontend: string | null;
            /** Frontend Broadcast */
            frontend_broadcast: string | null;
        };
        /** DurationStats */
        DurationStats: {
            /** Median */
            median: number | null;
            /** N */
            n: number;
            /** P90 */
            p90: number | null;
        };
        /** EditApprove */
        EditApprove: {
            /** Events */
            events: components["schemas"]["EditedEvent"][];
            /** Reason */
            reason?: string | null;
        };
        /** EditedEvent */
        EditedEvent: {
            /** Certainty */
            certainty?: ("stated" | "reported" | "speculative") | null;
            /** Payload */
            payload?: {
                [key: string]: unknown;
            } | null;
        };
        /** EngagementResult */
        EngagementResult: {
            /** Contact Id */
            contact_id?: string | null;
            /** Deal Id */
            deal_id: string;
            /** Event Id */
            event_id: string | null;
            /** Event Type */
            event_type: string;
            /** Proposal Id */
            proposal_id: string;
            /** Status */
            status: string;
        };
        /** Erasure */
        Erasure: {
            /** Reason */
            reason: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** NewBrief */
        NewBrief: {
            /**
             * Activate
             * @default false
             */
            activate: boolean;
            /** Change Note */
            change_note?: string | null;
            /** Yaml */
            yaml: string;
        };
        /** NextAction */
        NextAction: {
            /** Action */
            action: string;
            /**
             * Due Date
             * Format: date
             */
            due_date: string;
            /** Owner User Id */
            owner_user_id: string;
        };
        /**
         * NoContactRule
         * @description docs/05 scorer rule 6: a project in the engagement window with no contact found.
         */
        NoContactRule: {
            /** Applied */
            applied: boolean;
            /** Contact Found */
            contact_found: boolean;
            /** Contact Found By */
            contact_found_by: ("stage" | "engagement") | null;
            /** Contribution */
            contribution: number;
            /** Event Ids */
            event_ids: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** In Engagement Window */
            in_engagement_window: boolean;
            /** Project Stage */
            project_stage: string | null;
            /** Value */
            value: boolean;
            /** Weight */
            weight?: null;
        };
        /** Prequalification */
        Prequalification: {
            /** Buyer Id */
            buyer_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "not_started" | "submitted" | "approved" | "rejected";
        };
        /** PriorityBreakdown */
        PriorityBreakdown: {
            /** As Of */
            as_of: string;
            buyer_fit: components["schemas"]["PriorityPart"];
            confidence: components["schemas"]["PriorityPart"];
            demand: components["schemas"]["PriorityPart"];
            group: components["schemas"]["PriorityGroup"];
            lead_time: components["schemas"]["PriorityPart"];
            no_contact_boost: components["schemas"]["NoContactRule"];
            /** Parts */
            parts: string[];
            /** Project Id */
            project_id: string | null;
            /** Total */
            total: number;
            /** Version */
            version: string | null;
            /** Weighted Score */
            weighted_score: number;
        };
        /** PriorityGroup */
        PriorityGroup: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Order */
            order: number;
        };
        /** PriorityItem */
        PriorityItem: {
            /** Buyer Fit */
            buyer_fit: number | null;
            /** Confidence */
            confidence: number | null;
            /** Deal Type */
            deal_type: string | null;
            /** Demand Litres Month */
            demand_litres_month: number | null;
            /** Evidence Ids */
            evidence_ids: string[];
            /** Group Order */
            group_order: number;
            /** Group Rank */
            group_rank: number;
            /** Has Contact */
            has_contact: boolean;
            /** Id */
            id: string;
            /** Lead Time Days */
            lead_time_days: number | null;
            /** No Contact Rule */
            no_contact_rule: boolean;
            priority_breakdown: components["schemas"]["PriorityBreakdown"] | null;
            /** Priority Group */
            priority_group: string | null;
            /** Priority Score */
            priority_score: number | null;
            /** Project Id */
            project_id: string | null;
            /** Project Name */
            project_name: string | null;
            /** Rank */
            rank: number;
            /** Site Id */
            site_id: string | null;
            /** Site Name */
            site_name: string | null;
            /** Stage */
            stage: string;
            /** Stage Event Id */
            stage_event_id: string | null;
            /** Stage Evidence Ids */
            stage_evidence_ids: string[];
            /** Stage Pending */
            stage_pending: string | null;
            /** Title */
            title: string;
        };
        /** PriorityList */
        PriorityList: {
            /** Items */
            items: components["schemas"]["PriorityItem"][];
        };
        /**
         * PriorityPart
         * @description One part of the score: the value, the score (0 to 1), the weight, the contribution (score x weight), and the
         *     event ids and the evidence ids that it uses (docs/07 rule 1).
         */
        PriorityPart: {
            /** Contribution */
            contribution: number;
            /** Event Ids */
            event_ids: string[];
            /** Evidence Ids */
            evidence_ids: string[];
            /** Score */
            score: number;
            /** Value */
            value?: unknown;
            /** Weight */
            weight: number;
        };
        /** Proposal */
        Proposal: {
            /** Created At */
            created_at: string;
            /** Created By */
            created_by: string;
            /** Created By Me */
            created_by_me: boolean;
            /**
             * Created By Type
             * @enum {string}
             */
            created_by_type: "agent" | "human" | "system";
            /** Decided At */
            decided_at: string | null;
            /** Decided By */
            decided_by: string | null;
            /** Decision Reason */
            decision_reason: string | null;
            /** Events */
            events: components["schemas"]["ProposedEvent"][];
            /** Evidence */
            evidence: components["schemas"]["ProposalEvidence"][];
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Model Id */
            model_id: string | null;
            /**
             * Policy
             * @enum {string}
             */
            policy: "automatic" | "review" | "admin_review";
            /** Prompt Version */
            prompt_version: string | null;
            /** Source Id */
            source_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "approved" | "rejected" | "edited_approved" | "auto_approved";
            /** Stream Id */
            stream_id: string | null;
            /** Stream Type */
            stream_type: string | null;
            /** Summary */
            summary: string | null;
            /** Tier */
            tier: number | null;
            /** Title */
            title: string;
        };
        /**
         * ProposalEvidence
         * @description An evidence item of a proposal: the quote, the span offsets and the source link.
         */
        ProposalEvidence: {
            /** Char End */
            char_end: number;
            /** Char Start */
            char_start: number;
            /** Id */
            id: string;
            /** Published At */
            published_at?: string | null;
            /** Publisher */
            publisher?: string | null;
            /** Quote */
            quote: string;
            /** Retention Policy */
            retention_policy?: string | null;
            /** Source Id */
            source_id: string;
            /** Title */
            title?: string | null;
            /** Url */
            url?: string | null;
            /** Verified */
            verified: boolean;
        };
        /** ProposalList */
        ProposalList: {
            /** Items */
            items: components["schemas"]["Proposal"][];
            /** Total */
            total: number;
        };
        /** ProposedEvent */
        ProposedEvent: {
            /** Certainty */
            certainty?: ("stated" | "reported" | "speculative") | null;
            /** Event Type */
            event_type: string;
            /**
             * Evidence
             * @default []
             */
            evidence: components["schemas"]["ProposalEvidence"][];
            /**
             * Evidence Ids
             * @default []
             */
            evidence_ids: string[];
            /** Occurred At */
            occurred_at?: string | null;
            /** Payload */
            payload: {
                [key: string]: unknown;
            };
            /** Stream Id */
            stream_id: string;
            /** Stream Type */
            stream_type: string;
        };
        /** QuarantineList */
        QuarantineList: {
            /** Items */
            items: components["schemas"]["QuarantineRecord"][];
            /** Reason Codes */
            reason_codes: {
                [key: string]: string;
            };
            /** Total */
            total: number;
        };
        /** QuarantineRecord */
        QuarantineRecord: {
            /** Agent */
            agent: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Model Id */
            model_id: string | null;
            /** Output */
            output?: unknown | null;
            /** Prompt Version */
            prompt_version: string | null;
            /** Reason */
            reason: string | null;
            /** Reason Code */
            reason_code: string;
            /** Run Id */
            run_id: string | null;
            /** Source Id */
            source_id: string | null;
            /** Source Title */
            source_title?: string | null;
            /** Source Url */
            source_url?: string | null;
        };
        /** RejectResult */
        RejectResult: {
            /** Proposal Id */
            proposal_id: string;
            /**
             * Status
             * @constant
             */
            status: "rejected";
        };
        /** Rejection */
        Rejection: {
            /** Reason */
            reason: string;
        };
        /** RuleRate */
        RuleRate: {
            /** Alerts */
            alerts: number;
            /** Confirmed */
            confirmed: number;
            /** Decided */
            decided: number;
            /** Dismissed */
            dismissed: number;
            /** False Positive */
            false_positive: number;
            /** False Positive Rate */
            false_positive_rate: number | null;
            /** Tier */
            tier: number;
            /** Tier Rule */
            tier_rule: string;
        };
        /** StageMove */
        StageMove: {
            /** Reason */
            reason?: string | null;
            /** To Stage */
            to_stage: string;
        };
        /** StageMoveResult */
        StageMoveResult: {
            /** Deal Id */
            deal_id: string;
            /** Proposal Id */
            proposal_id: string;
            /** Stage */
            stage: string;
            /** Stage Pending */
            stage_pending: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "approved";
        };
        /** Telemetry */
        Telemetry: {
            /** Items */
            items: components["schemas"]["TelemetryAlert"][];
            metrics: components["schemas"]["TelemetryMetrics"];
        };
        /** TelemetryAlert */
        TelemetryAlert: {
            /** Acknowledged At */
            acknowledged_at: string | null;
            /** Acknowledged By */
            acknowledged_by: string | null;
            /** Decided At */
            decided_at: string | null;
            /** Decided By */
            decided_by: string | null;
            /** Decision Reason */
            decision_reason: string | null;
            delivered: components["schemas"]["DeliveryTimes"];
            delivery_status: components["schemas"]["DeliveryStatus"];
            /** Fetched At */
            fetched_at: string | null;
            /** Id */
            id: string;
            /** Latency Fetch To Alert Seconds */
            latency_fetch_to_alert_seconds: number | null;
            /** Latency Publish To Alert Seconds */
            latency_publish_to_alert_seconds: number | null;
            /** Outcome */
            outcome: ("confirmed" | "dismissed" | "false_positive") | null;
            /** Published At */
            published_at: string | null;
            /** Raised At */
            raised_at: string;
            /** Signal Id */
            signal_id: string | null;
            /** Source Id */
            source_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "unconfirmed" | "confirmed" | "dismissed" | "false_positive";
            /** Tier */
            tier: number;
            /** Tier Rule */
            tier_rule: string;
            /** Time To Acknowledgement Seconds */
            time_to_acknowledgement_seconds: number | null;
            /** Title */
            title: string;
        };
        /** TelemetryMetrics */
        TelemetryMetrics: {
            /** False Positive Rate By Tier Rule */
            false_positive_rate_by_tier_rule: components["schemas"]["RuleRate"][];
            latency_fetch_to_alert_seconds: components["schemas"]["DurationStats"];
            time_to_acknowledgement_seconds: components["schemas"]["DurationStats"];
        };
        /** Touchpoint */
        Touchpoint: {
            /** Contact Id */
            contact_id?: string | null;
            /**
             * Date
             * Format: date
             */
            date: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "call" | "meeting" | "email" | "site_visit";
            /** Note */
            note: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Decision */
        services__api__routers__governance__Decision: {
            /** Reason */
            reason?: string | null;
        };
        /** Decision */
        services__api__routers__sources__Decision: {
            /** Reason */
            reason?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    alerts_api_alerts_get: {
        parameters: {
            query?: {
                status?: string[] | null;
                tier?: number | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_alert_api_alerts__alert_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_alert_api_alerts__alert_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AlertConfirm"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_alert_api_alerts__alert_id__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertDismiss"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_briefs_api_briefs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_brief_api_briefs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewBrief"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    brief_diff_api_briefs_diff_get: {
        parameters: {
            query: {
                from: number;
                to: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_brief_api_briefs__version__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_brief_api_briefs__version__activate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_api_calendar_get: {
        parameters: {
            query?: {
                months?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stages_api_config_stages_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    taxonomy_api_config_taxonomy_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    deals_api_deals_get: {
        parameters: {
            query?: {
                stage?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deal_detail_api_deals__deal_id__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_contact_api_deals__deal_id__contacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Contact"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngagementResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_next_action_api_deals__deal_id__next_action_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NextAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngagementResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_prequalification_api_deals__deal_id__prequalification_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Prequalification"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngagementResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deal_relationship_api_deals__deal_id__relationship_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_stage_api_deals__deal_id__stage_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageMove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageMoveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    log_touchpoint_api_deals__deal_id__touchpoints_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Touchpoint"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngagementResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    demand_drivers_api_demand_drivers_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entities_api_entities_get: {
        parameters: {
            query?: {
                type?: string | null;
                q?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_detail_api_entities__entity_id__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                entity_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evidence_api_evidence_get: {
        parameters: {
            query: {
                ids: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    live_api_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    map_layers_api_map_get: {
        parameters: {
            query?: {
                site_class?: string[] | null;
                stage?: string[] | null;
                sector?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_person_api_persons__person_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    erase_person_api_persons__person_id__erase_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                person_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Erasure"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    priority_api_priority_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PriorityList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    projects_api_projects_get: {
        parameters: {
            query?: {
                stage?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    project_detail_api_projects__project_id__get: {
        parameters: {
            query?: {
                as_of?: string | null;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proposals_api_proposals_get: {
        parameters: {
            query?: {
                status?: ("pending" | "approved" | "rejected" | "edited_approved" | "auto_approved")[] | null;
                kind?: string[] | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_proposal_api_proposals__proposal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Proposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_proposal_api_proposals__proposal_id__approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["services__api__routers__governance__Decision"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_source_api_proposals__proposal_id__approve_source_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["services__api__routers__sources__Decision"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_approve_proposal_api_proposals__proposal_id__edit_approve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EditApprove"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApproveResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reject_proposal_api_proposals__proposal_id__reject_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Rejection"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_quarantine_api_quarantine_get: {
        parameters: {
            query?: {
                reason_code?: string | null;
                agent?: string | null;
                source_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantineList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quarantine_api_quarantine__quarantine_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quarantine_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuarantineRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_login_api_session_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    session_logout_api_session_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    signals_api_signals_get: {
        parameters: {
            query?: {
                tier?: number[] | null;
                sector?: string[] | null;
                geography?: string[] | null;
                theme?: string[] | null;
                entity_id?: string | null;
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sites_api_sites_get: {
        parameters: {
            query?: {
                watch?: string;
                site_class?: string[] | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_health_api_sources_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    known_gaps_api_sources_known_gaps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    manual_upload_api_sources_manual_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Licence Code */
                    licence_code?: string | null;
                    /** Publisher */
                    publisher?: string | null;
                    /** Title */
                    title?: string | null;
                    /** Url */
                    url: string;
                };
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    licence_code?: string;
                    publisher?: string;
                    title?: string;
                    url?: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_source_api_sources__source_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                source_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    alert_telemetry_api_telemetry_alerts_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Telemetry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ticker_api_ticker_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timeline_api_timeline_get: {
        parameters: {
            query: {
                stream_type: string;
                stream_id: string;
                as_of?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
